### ISSUE TITLE
Uncaught Error: Cannot find module 'cson'

### ISSUE THREAD

**Issue by mengzhuwu** [Sheng-Bo/atom-cht-menu#5]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.6.1
**System**: Mac OS X 10.11.1
**Thrown From**: [cht-menu](https://github.com/Sheng-Bo/atom-cht-menu) package, v0.1.13
### Stack Trace

Uncaught Error: Cannot find module 'cson'

```
At module.js:338

Error: Cannot find module 'cson'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Users/mengzhuwu/Desktop/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Users/mengzhuwu/Desktop/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at module.exports.delay (/Users/mengzhuwu/.atom/packages/atom-cht-menu-master/lib/main.coffee:8:12)
```
### Commands

```
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by Sheng-Bo** [comment]
This issue could be solved when you update to the latest version of Atom (e.g., 1.7.3).
